services:
  localstack:
    image: localstack/localstack:3.1.0
    environment:
      - IMAGE_NAME=localstack/localstack:3.1.0
      - SERVICES=sns,sqs
      - DEBUG=0
      - DISABLE_CORS_CHECKS=1
      - PARITY_AWS_ACCESS_KEY_ID=1
    ports:
      - '4566:4566'
      - '4570-4597:4570-4597'
  awscli:
      image: amazon/aws-cli:2.15.18
      depends_on:
        - localstack
      environment:
        - AWS_DEFAULT_REGION=eu-west-1
        - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
        - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
        - AWS_ENDPOINT_URL=http://localstack:4566
        - AWS_DEFAULT_OUTPUT=table
      entrypoint: /bin/sh -c
      command: >
        "
            sleep 5s
            aws sqs create-queue --queue-name generic-status-monitor.fifo --attributes FifoQueue=true,ContentBasedDeduplication=false
        "