name: Status Monitor

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: gimlichael/pipelines/.github/actions/install-dotnet@main
      - uses: gimlichael/pipelines/.github/actions/install-dotnet-tool-minver@main
      - uses: gimlichael/pipelines/.github/actions/install-dotnet-tool-reportgenerator@main
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
